# Generated by Django 3.2.12 on 2023-02-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_student_parent_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_name',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_phone',
            new_name='emergency_contact_phone',
        ),
    ]
