# Generated by Django 3.2.12 on 2023-02-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_subject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('max_unit_load', models.IntegerField()),
                ('min_unit_load', models.IntegerField()),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.level')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.teacher')),
            ],
        ),
    ]
